### ISSUE TITLE
Does this cope with Prokka GFF3 files ok?

### ISSUE THREAD

**Issue by tseemann** [sanger-pathogens/gff3toembl#23]
Does the GFF3 file that Prokka produces satisfy the input requirements for this script?

I would really like to ditch tbl2asn !

**Comment by andrewjpage** [comment]
Yes, it's actually only been tested with prokka gff3 files, and has been
used for 11,000 submissions. It requires genome tools, which will only work
on Linux(which is probably a show stopper).
Andrew

**Comment by satta** [comment]
Actually the GenomeTools Python bindings (which indeed had problems on other platforms) have recently been fixed (https://github.com/genometools/genometools/issues/211) to the point where at least the Python testsuite passes now on Mac OS X as well. I didn't try it with gff3toembl yet, but if you try just let me know if anything fails.

**Comment by tseemann** [comment]
I've just moved jobs, and setting up from scratch. Decided to use LinuxBrew for package management, as the team have already done lots of homebrew-science formulae, which I am slowly adding to.

(genometools is in Brew, but if fails on LinuxBrew.)
