### ISSUE TITLE
OSX and dlylib

### ISSUE THREAD

**Issue by mcnelsonphd** [sanger-pathogens/gff3toembl#33]
On OS X, setting an explicit path for DYLD_LIBRARY_PATH isn't a great idea.

Instead, you should be instructing people to just create a symlink for libgenometools.dylib in /usr/lib that points to wherever the file is located. This is simpler in my opinion and removes any chance that a user setting an explicit search path will screw up anything else on their system.

**Comment by andrewjpage** [comment]
Thanks for the feedback, I'll update the documentation now.
