### ISSUE TITLE
v1.0.0 vs v1.0

### ISSUE THREAD

**Issue by sjackman** [sanger-pathogens/gff3toembl#36]
It's quite confusing to have two versions tagged that differ by `.0`. Consider deleting one of the two tags.

**Comment by sjackman** [comment]
See [Semantic Versioning](http://semver.org/)

**Comment by andrewjpage** [comment]
The v1.0 tag is gone now. Thanks for flagging it.

**Comment by sjackman** [comment]
No worries. Thanks, Andrew.
