### ISSUE TITLE
Failure to install on Biolinux

### ISSUE THREAD

**Issue by dutchscientist** [sanger-pathogens/gff3toembl#38]
I have tried to install via LinuxBrew and this fails on the fontconfig (see https://github.com/Homebrew/homebrew/issues/45260). Have tried to install via git, and then run the install dependencies shellscript, and then python setup.py install. Setuptools is installed, and then run it, error message received:

All fine, but 

Traceback (most recent call last):
  File "/usr/local/bin/gff3_to_embl", line 5, in <module>
    pkg_resources.run_script('gff3toembl==1.0.1', 'gff3_to_embl')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/gff3toembl-1.0.1-py2.7.egg/EGG-INFO/scripts/gff3_to_embl", line 8, in <module>
    
  File "build/bdist.linux-x86_64/egg/gff3toembl/EMBLWriter.py", line 3, in <module>
ImportError: No module named gt

Where am I going wrong? Thanks :)

**Comment by andrewjpage** [comment]
The main dependancy is genome tools. You can install it via linuxbrew:
brew install genometools

Or on modern Debian based systems:
apt-get install python-genometools

**Comment by dutchscientist** [comment]
When installing genometools via Brew it crashes on the fontconfig as well, and when installed via apt-get it installs but then gives the above errors. Tried it on two different independent biolinux setups.

Will give it a shot on a different Linux distribution, to see whether it is BioLinux-related.

**Comment by dutchscientist** [comment]
Have tried different Ubuntu (out of the box) and no joy, same error messages. Which Linux version are you using?

**Comment by tseemann** [comment]
Yes it seems a lot of Linuxbrew has broken while Shaun Jackman is on 2 months holiday leave. This includes `fontconfig`, `harfbuzz` and others which `genometools` needs. Also, I am not sure if the `genometools` python libraries are being installed properly!

**Comment by dutchscientist** [comment]
In a way I am pleased to hear it ainkt my incompetence. I would like to see it function though!I have tried to use the Zip, but that failed on the dependencies.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Torsten SeemannSent: Saturday, 5 December 2015 21:27To: sanger-pathogens/gff3toemblReply To: sanger-pathogens/gff3toemblCc: dutchscientistSubject: Re: [gff3toembl] Failure to install on Biolinux (#38)Yes it seems a lot of Linuxbrew has broken while Shaun Jackman is on 2 months holiday leave. This includes fontconfig, harfbuzz and others which genometools needs. Also, I am not sure if the genometools python libraries are being installed properly!

—Reply to this email directly or view it on GitHub.

**Comment by satta** [comment]
Interesting! I don;t know about Linuxbrew, but at least the Debian/Ubuntu package should work... 
After installing `python-genometools` (what version?) what does happen if you run the following:
```
$ python -c 'import gt; print(gt)'
```
If installed correctly, you should get something like:
```
$ python -c 'import gt; print(gt)'
<module 'gt' from '/usr/lib/python2.7/dist-packages/gt/__init__.pyc'>
```

**Comment by dutchscientist** [comment]
I get:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/gt/__init__.py", line 30, in
<module>
    from annotationsketch import *
  File "/usr/lib/python2.7/dist-packages/gt/annotationsketch/__init__.py",
line 20, in <module>
    from block import *
  File "/usr/lib/python2.7/dist-packages/gt/annotationsketch/block.py",
line 20, in <module>
    from gt.dlload import gtlib
  File "/usr/lib/python2.7/dist-packages/gt/dlload.py", line 30, in <module>
    gtlib = CDLL("libgenometools" + soext)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libgenometools.so: cannot open shared object file: No such file or
directory

I also tried "sudo apt-get install python-genometools", it installs fine
but no dice in running...

**Comment by satta** [comment]
What if you also `apt-get install libgenometools0`? Does help? It should get pulled in as a dependency by `python-genometools` but you don't seem to have it...

**Comment by dutchscientist** [comment]
Libgenometools0 is installed, the only effect is that it is set to manual
install.

**Comment by satta** [comment]
Weird .Can you try to `apt-get install --reinstall libgenometools0` and then please confirm the presence of any `libgenometools.so.*` file in `/usr/lib`?

**Comment by dutchscientist** [comment]
I have libgenometools.so.0 in /usr/lib, no other genometools files there
(should there be?).

That's after reinstall, no change in the error message :-(

**Comment by satta** [comment]
There seems to be the problem, you should have a `libgenometools.so` symlink in there pointing to the library. Like this:
```
[vagrant@vagrant-debian-jessie:/usr/lib] $ ll libgenome*
lrwxrwxrwx 1 root root      19 Sep  5  2014 libgenometools.so -> libgenometools.so.0
-rw-r--r-- 1 root root 5337368 Sep  5  2014 libgenometools.so.0
```
Can you please also try installing `libgenometools0-dev` and see if it works then?

**Comment by dutchscientist** [comment]
Brilliant, installing libgenometools0-dev makes it work! Much appreciated :-)

 

Now I get a normal response to the script:

 

vanvlia@server:~$ gff3_to_embl -h

usage: gff3_to_embl [-h] [--authors AUTHORS] [--title TITLE]

                    [--publication PUBLICATION] [--genome_type GENOME_TYPE]

                    [--classification CLASSIFICATION]

                    [--output_filename OUTPUT_FILENAME]

                    [--locus_tag LOCUS_TAG]

                    [--translation_table TRANSLATION_TABLE]

                    [--chromosome_list CHROMOSOME_LIST] [--version]

                    organism taxonid project_accession description file

 

Converts prokaryote GFF3 annotations to EMBL for ENA submission.

 

positional arguments:

  organism              Organism

  taxonid               Taxon id

  project_accession     Accession number for the project

  description           Genus species subspecies strain of organism

  file                  GFF3 filename

 

optional arguments:

  -h, --help            show this help message and exit

  --authors AUTHORS, -i AUTHORS

                        Authors

  --title TITLE, -m TITLE

                        Title of paper

  --publication PUBLICATION, -p PUBLICATION

                        Publication

  --genome_type GENOME_TYPE, -g GENOME_TYPE

                        Genome type (linear/circular)

  --classification CLASSIFICATION, -c CLASSIFICATION

                        Classification (PROK/UNC/..)

  --output_filename OUTPUT_FILENAME, -f OUTPUT_FILENAME

                        Output filename

  --locus_tag LOCUS_TAG, -l LOCUS_TAG

                        Overwrite the locus tag in the annotation file

  --translation_table TRANSLATION_TABLE, -n TRANSLATION_TABLE

                        Translation table

  --chromosome_list CHROMOSOME_LIST, -d CHROMOSOME_LIST

                        Create a chromosome list file, and use the supplied

                        name

  --version             show program's version number and exit

 

Time to try it for real! Worth adding this to the install page?

 

I will try it on a clean Ubuntu install as well, see whether this added instructions fixes it, will report back on it :-)

**Comment by dutchscientist** [comment]
OK, so it installs fine, but still fails several tests and does not want to work with a Prokka generated GFF3 file.

Command line:
gff3_to_embl --authors 'Arnoud' --title 'fsa_ccoli_test' --publication 'journal' --genome_type 'circular' --classification 'PROK' --output_filename
 LDI4897.embl --translation_table 11 Campylobacter 195 'FSA Ccoli' 'My description' CL2_LDI4897.gff

Errors given:
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/usr/lib/python2.7/dist-packages/gt/extended/custom_stream.py", line 41, in next_w
    nextnode = self.next()
  File "build/bdist.linux-x86_64/egg/gff3toembl/VisitorStream.py", line 12, in next
  File "/usr/lib/python2.7/dist-packages/gt/extended/genome_stream.py", line 51, in next_tree
    gterror(err)
  File "/usr/lib/python2.7/dist-packages/gt/core/error.py", line 80, in gterror
    raise GTError, "GenomeTools error: " + err.get()
gt.core.error.GTError: GenomeTools error: the file CL2_LDI4897.gff_fixed.gff is not sorted (example: line 5602 and 5603)
Assertion failed: (err && err->error_is_set), function gt_error_get, file src/core/error.c, line 72.
This is a bug, please report it.
bug: file pointer leaked (opened on line 147 in file "src/core/file.c")

On another system it still says GT is not there in /bin/sh

*sigh*

(but good progress!)

**Comment by satta** [comment]
This sounds like something `gff3toembl` should probably be doing in preprocessing but from a GenomeTools point of view it might help if you sort your GFF3 file first using:
```
gt gff3 -sort -retainids -tidy  CL2_LDI4897.gff >  CL2_LDI4897.sorted.gff3
```
and than work with that.

**Comment by andrewjpage** [comment]
The first step runs:
gt gff3 -force -sort -retainids -tidy -o xxxx.gff_fixed.gff inputfile.gff
and from the error message it is trying to read in this fixed, sorted file,
so theres something else going on?

Andrew

**Comment by dutchscientist** [comment]
The install_dependencies.sh script installed the genometools package. 

I have tried the tidying/sorting, no dice:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/usr/lib/python2.7/dist-packages/gt/extended/custom_stream.py", line 41, in next_w
    nextnode = self.next()
  File "build/bdist.linux-x86_64/egg/gff3toembl/VisitorStream.py", line 12, in next
  File "/usr/lib/python2.7/dist-packages/gt/extended/genome_stream.py", line 51, in next_tree
    gterror(err)
  File "/usr/lib/python2.7/dist-packages/gt/core/error.py", line 80, in gterror
    raise GTError, "GenomeTools error: " + err.get()
gt.core.error.GTError: GenomeTools error: the file CL2_LDI4897.sorted.gff3_fixed.gff is not sorted (example: line 5602 and 5603)
Assertion failed: (err && err->error_is_set), function gt_error_get, file src/core/error.c, line 72.
This is a bug, please report it.
bug: file pointer leaked (opened on line 147 in file "src/core/file.c")

The GFF3 file comes straight from a Prokka output (and has been used in Roary without problem), but the sorting does not seem to help.

**Comment by satta** [comment]
Hmmm, could I have a look at your file? It could be that the content itself makes the result appear not sorted. The lines mentioned (5602 and 5603) and their surrounding context are probably most interesting there.

**Comment by dutchscientist** [comment]
Of course.

Downloadable from Google Drive:

https://drive.google.com/file/d/0BzVZejrtim6ROE5fQVh4WjlJY2s/view?usp=sharing
(pre-sorting)
https://drive.google.com/file/d/0BzVZejrtim6RcUFaZjdOdWxCWVE/view?usp=sharing
(after sorting)

Have tried others as well.

**Comment by satta** [comment]
Weird, I can't reproduce that here in my environment:
```
[satta@tortuga:~gt] $ DYLD_LIBRARY_PATH=./lib gff3_to_embl foo 1234 1111 baz CL2_LDI4897.gff
[satta@tortuga:~gt] $ ll output.embl
-rw-r--r--  1 satta  staff  2635639 19 Dec 13:04 output.embl
```
The run finishes and the output file is there.

 Could it be a result of your having mixed installations from multiple sources? Can you confirm you also have the `gt` binary in your `$PATH`? It could be that the Python module is picking up the library but `gff3toembl` also calls the `gt` executable to sort the file, and if that is missing you might get funny results.

**Comment by dutchscientist** [comment]
$ which gt
/usr/bin/gt

Looks fine. I also had the problems on clean installs; I'll try one more clean Ubuntu install in Virtualbox, without the Linuxbrew.

**Comment by dutchscientist** [comment]
Nope, no luck. Did not touch Linuxbrew, gt runs fine but still the same error message:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/usr/lib/python2.7/dist-packages/gt/extended/custom_stream.py", line 41, in next_w
    nextnode = self.next()
  File "build/bdist.linux-x86_64/egg/gff3toembl/VisitorStream.py", line 12, in next
  File "/usr/lib/python2.7/dist-packages/gt/extended/genome_stream.py", line 51, in next_tree
    gterror(err)
  File "/usr/lib/python2.7/dist-packages/gt/core/error.py", line 80, in gterror
    raise GTError, "GenomeTools error: " + err.get()
gt.core.error.GTError: GenomeTools error: the file C670_0828.gff_fixed.gff_fixed.gff is not sorted (example: line 5664 and 5665)
Assertion failed: (err && err->error_is_set), function gt_error_get, file src/core/error.c, line 72.
This is a bug, please report it.
bug: file pointer leaked (opened on line 147 in file "src/core/file.c")

It almost suggests a dependency somewhere or a Python error.

**Comment by dutchscientist** [comment]
I have also tried it in the Roary Virtual Machine offered (see the Roary github page), with the same results. That gives you a good testing system to reproduce it.

**Comment by satta** [comment]
OK, I'll see what I can do. How exactly did you install gff3toembl and its dependencies in the Roary VM?
I will be on holiday next week but will look into it afterwards.

**Comment by dutchscientist** [comment]
Import the VM, and then:

- Download gff3toembl-master.zip
- sudo apt-get update
- sudo apt-get upgrade
- cd Downloads
- unzip gff3toembl-master.zip
- cd gff3toembl-master
- chmod +x install_dependencies.sh
- sudo ./install_dependencies.sh
- sudo python setup.py test (fails on ubuntu due to claimed absence/incompatability setuptools)
- sudo python setup.py install
- cd ..
- gff3_to_embl -h (fails on "ImportError: No module named gt")
- sudo apt-get install genometools
- gff3_to_embl -h (fails on "ImportError: No module named gt")
- sudo apt-get install python-genometools
- sudo apt-get install libgenometools0-dev
- gff3_to_embl -h (works fine, gives helptext)
- gff3_to_embl foo 1234 1111 baz CL2_LDI4897.gff (error)

Tried a few different files, makes no difference.

No rush, would like to see it working. Enjoy the holidays :-)

**Comment by dutchscientist** [comment]
Interesting: the install_dependencies shell installs v 1.5.5 of GenomeTools, but that is an older version. I'll try once more, but now manually installing the new version as suggested in https://github.com/tseemann/prokka/issues/145

**Comment by dutchscientist** [comment]
Ouch, this works on the pathogens-VM!

So the steps to take are:

- download the ZIPs from https://github.com/genometools/genometools and https://github.com/sanger-pathogens/gff3toembl
- open terminal, go to Download location (cd Downloads)
- unzip genometools-master.zip
- cd genometools-master
- make -j4 cairo=no
- sudo make -j4 install cairo=no
- sudo apt-get install python-genometools
- cd ..
- unzip gff3toembl-master.zip
- cd gff3toembl-master
- do NOT use the install-dependencies.sh! Installs old version of GT
- sudo python setup.py install
- cd ..

I rebooted for some maintenance. Then in terminal with testfile 4006_0045.gff (straight from Prokka, no sorting):
- gff3_to_embl foo 1234 1111 baz 4006_0045.gff -f 4006_0045.embl

And eureka! EMBL file made without any protest.

I recommend correcting the installation instructions :-)

**Comment by dutchscientist** [comment]
So now the question is, how can I remove the broken installation from my server? That has the Linuxbrew attempts and the install-dependencies.sh files installed. I have tried to uninstall the genometools, but still get the errormessages.

**Comment by andrewjpage** [comment]
Corrected by this: 
https://github.com/sanger-pathogens/gff3toembl/issues/59
