### ISSUE TITLE
self.assertItemsEqual is Python 2.7 only

### ISSUE THREAD

**Issue by peterjc** [sanger-pathogens/gff3toembl#43]
You could use ``self.assertCountEqual`` under Python 3 (see #40), or just replace it with explicit sorting and call the generic ``unittest`` method ``self.assertEqual`` instead?

**Comment by andrewjpage** [comment]
We'll come back to this if genometools gets python 3 bindings. We just have to convince @satta

**Comment by satta** [comment]
I remember I started making it Python 3 compliant a while ago:
```
$ git log gtpython3 -1                                      [master] [0]
commit eca9ea465fe8bed3070ecb442f0e498ffa9bbe8c
Author: Sascha Steinbiss <steinbiss@zbh.uni-hamburg.de>
Date:   Tue Jan 8 09:54:02 2013 +0100

    more python3 fixes
```
so I might want to revisit that branch soon... maybe there is not much left to do.
