### ISSUE TITLE
mac brew install does not work.

### ISSUE THREAD

**Issue by andersgs** [sanger-pathogens/gff3toembl#63]
It seems the `libpng` dependency is out of date:

![brew_install](https://cloud.githubusercontent.com/assets/3836603/18910007/747bfe30-85b9-11e6-83a5-170641c48072.jpg)

**Comment by andrewjpage** [comment]
Hi Anders,
Could you run "brew update" and try it again?  The latest version of libpng is 1.6.25 and your recipe is trying to download is 1.6.17.
Andrew
