### ISSUE TITLE
Installation and running problems

### ISSUE THREAD

**Issue by apredeus** [sanger-pathogens/gff3toembl#74]
Hello all, 

I'm having problems installing and running gff3toembl. First of all, installation of python-genometools does not make python gt module available - any ideas why? 

```
sudo apt-get install python-genometools
python -c 'import gt; print(gt)'
```
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ImportError: No module named gt

Second, when I try to run the tool from the docker container, I get an error message that I have no idea how to debug: 

```
fopen(): cannot open file '/home/apredeus/EMBL/ENA_D23/D23580_liv.prokka.gff_fixed.gff': No such file or directory
Failed to sort and tidy gff file with GT
```

I would appreciate any help.

**Comment by satta** [comment]
Are you probably using Python 3 as your `python`? The `python-genometools` package only installs Python 2 modules.

**Comment by apredeus** [comment]
Not quite, but you were close - it was conda's python2 that was called instead of the default system's one. 

It did work after this got fixed, thank you.

**Comment by ireneortega** [comment]
I have the same two problems. How can I solve it?
